const productsListEl = document.querySelector('#products-list .products-list');
export const categorySelectEl = document.querySelector('#categories');
export const productListEl = document.querySelector('.products-list');
export const closeModalBtn = document.querySelector('[data-modal-close]');
export const modalEl = document.querySelector('[data-modal]');
export const popularListEl = document.querySelector('.popular-list');
export const discountProductsEl = document.querySelector('.discount-products');
export const filtersFormEL = document.querySelector('.filters-form-search')
export default { productsListEl };